// Generated by CIRCT unknown git version
module simple_example(	// ./out/comp/affine.mlir:1:3
  output        x_p0_addr_en,
  output [6:0]  x_p0_addr_data,
  output        x_p0_wr_en,
  output [31:0] x_p0_wr_data,
  input         t,
                clk,
                rst
);

  wire [63:0] _GEN;
  wire        _GEN_0;
  wire [31:0] _GEN_1;
  wire        _GEN_2;
  reg         _GEN_3;
  wire [31:0] _GEN_4;
  wire        _GEN_5;
  wire [63:0] _reg_1x64_r0_w1_inst1_p0_rd_data;
  wire [31:0] _add_i32_inst0_out;	// ./out/comp/affine.mlir:8:12
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_2),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_5),
    .p1_wr_data (_GEN_4),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_5 = t ? 1'h1 : _GEN_2;
  assign _GEN_4 = t ? 32'h0 : _GEN_1;
  wire        _GEN_6 = t & 1'h1 | _GEN_3 & ~_ForOP_SM0_done;	// ./out/comp/affine.mlir:6:5
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h80),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_6),	// ./out/comp/affine.mlir:6:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_3 <= 1'h0;
    else
      _GEN_3 <= _GEN_6;	// ./out/comp/affine.mlir:6:5
  end // always_ff @(posedge)
  assign _GEN_2 = _GEN_3 ? 1'h1 : 1'h0;
  add_i32 add_i32_inst0 (	// ./out/comp/affine.mlir:8:12
    .a   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .b   (32'h1),
    .t   (_GEN_3),
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst0_out)
  );
  assign _GEN_1 = _GEN_3 ? _add_i32_inst0_out : 32'bx;	// ./out/comp/affine.mlir:8:12
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst1 (
    .p0_rd_en   (_GEN_2),
    .p0_rd_data (_reg_1x64_r0_w1_inst1_p0_rd_data),
    .p1_wr_en   (_GEN_0),
    .p1_wr_data (_GEN),
    .t          (_GEN_6),	// ./out/comp/affine.mlir:6:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_0 = _GEN_6 ? 1'h1 : 1'h0;	// ./out/comp/affine.mlir:6:5
  assign _GEN = _GEN_6 ? _ForOP_SM0_iv : 64'bx;	// ./out/comp/affine.mlir:6:5
  wire [63:0] _GEN_7 = _reg_1x64_r0_w1_inst1_p0_rd_data * 64'h1 + 64'h0;
  assign x_p0_addr_en = _GEN_2;
  assign x_p0_addr_data = _GEN_3 ? _GEN_7[6:0] : 7'bx;
  assign x_p0_wr_en = _GEN_2;
  assign x_p0_wr_data = _GEN_3 ? _add_i32_inst0_out : 32'bx;	// ./out/comp/affine.mlir:8:12
endmodule

