// Generated by CIRCT unknown git version
module stencil_2d(	// ./stencil_2d_out/comp/affine.mlir:1:1
  output        orig_p0_addr_en,
  output [9:0]  orig_p0_addr_data,
  output        orig_p0_rd_en,
  input  [31:0] orig_p0_rd_data,
  output        filter_p0_addr_en,
  output [3:0]  filter_p0_addr_data,
  output        filter_p0_rd_en,
  input  [31:0] filter_p0_rd_data,
  output        sol_p0_addr_en,
  output [9:0]  sol_p0_addr_data,
  output        sol_p0_wr_en,
  output [31:0] sol_p0_wr_data,
  input         t,
                clk,
                rst
);

  wire        _GEN;
  wire [63:0] _GEN_0;
  wire        _GEN_1;
  wire        _GEN_2;
  reg         _GEN_3;
  wire        _GEN_4;
  wire [63:0] _GEN_5;
  wire        _GEN_6;
  wire [63:0] _GEN_7;
  wire [63:0] _GEN_8;
  wire [31:0] _GEN_9;
  wire        _GEN_10;
  wire        _GEN_11;
  wire        _GEN_12;	// ./stencil_2d_out/comp/affine.mlir:10:16
  wire        _GEN_13;	// ./stencil_2d_out/comp/affine.mlir:9:9
  wire [31:0] _GEN_14;
  wire        _GEN_15;
  wire [63:0] _reg_1x64_r0_w1_inst4_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst3_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst2_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst1_p0_rd_data;
  wire [31:0] _add_i32_inst1_out;	// ./stencil_2d_out/comp/affine.mlir:14:16
  wire [31:0] _mul_i32_inst0_out;	// ./stencil_2d_out/comp/affine.mlir:13:16
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire [63:0] _ForOP_SM1_iv;
  wire        _ForOP_SM1_done;
  wire [63:0] _ForOP_SM2_iv;
  wire        _ForOP_SM2_done;
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_11),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_15),
    .p1_wr_data (_GEN_14),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  wire        _GEN_16 = t & 1'h1 | _GEN_3 & ~_ForOP_SM2_done;	// ./stencil_2d_out/comp/affine.mlir:6:5
  ForOp_state_machine2 ForOP_SM2 (
    .lb    (64'h0),
    .ub    (64'h1C),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_16),	// ./stencil_2d_out/comp/affine.mlir:6:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM2_iv),
    .done  (_ForOP_SM2_done)
  );
  reg         _GEN_17;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_17 <= 1'h0;
    else
      _GEN_17 <= _GEN_16;	// ./stencil_2d_out/comp/affine.mlir:6:5
  end // always_ff @(posedge)
  assign _GEN_15 = _GEN_17 ? 1'h1 : _GEN_10;
  assign _GEN_14 = _GEN_17 ? 32'h0 : _GEN_9;
  wire        _GEN_18 = 64'h0 < 64'h3;
  wire        _GEN_19 = _GEN_16 & _GEN_18;	// ./stencil_2d_out/comp/affine.mlir:6:5
  wire        _GEN_20 = _GEN_19 | _GEN_13 & ~_ForOP_SM1_done;	// ./stencil_2d_out/comp/affine.mlir:8:7, :9:9
  wire        _GEN_21 = _GEN_16 & ~_GEN_18;	// ./stencil_2d_out/comp/affine.mlir:6:5
  wire [63:0] _GEN_22 = _GEN_19 ? _ForOP_SM2_iv : _reg_1x64_r0_w1_inst3_p0_rd_data;
  ForOp_state_machine1 ForOP_SM1 (
    .lb    (64'h0),
    .ub    (64'h3),
    .step  (64'h1),
    .start (_GEN_16),	// ./stencil_2d_out/comp/affine.mlir:6:5
    .next  (_GEN_20),	// ./stencil_2d_out/comp/affine.mlir:8:7
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM1_iv),
    .done  (_ForOP_SM1_done)
  );
  wire        _GEN_23 = _GEN_20 & _GEN_18;	// ./stencil_2d_out/comp/affine.mlir:8:7
  wire        _GEN_24 = _GEN_23 | _GEN_12 & ~_ForOP_SM0_done;	// ./stencil_2d_out/comp/affine.mlir:9:9, :10:16
  wire        _GEN_25 = _GEN_20 & ~_GEN_18;	// ./stencil_2d_out/comp/affine.mlir:8:7
  assign _GEN_13 = _GEN_25 | _GEN_12 & _ForOP_SM0_done;	// ./stencil_2d_out/comp/affine.mlir:9:9, :10:16
  wire [63:0] _GEN_26 = _GEN_23 ? _ForOP_SM1_iv : _reg_1x64_r0_w1_inst1_p0_rd_data;
  wire [63:0] _GEN_27 = _GEN_23 ? _GEN_22 : _reg_1x64_r0_w1_inst2_p0_rd_data;
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h3),
    .step  (64'h1),
    .start (_GEN_20),	// ./stencil_2d_out/comp/affine.mlir:8:7
    .next  (_GEN_24),	// ./stencil_2d_out/comp/affine.mlir:9:9
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  reg  [1:0]  _GEN_28;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_28 <= {2{1'h0}};
    else
      _GEN_28 <= {_GEN_28[1'h0 +: 1], {1{_GEN_24}}};	// ./stencil_2d_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  assign _GEN_12 = _GEN_28[1'h1];	// ./stencil_2d_out/comp/affine.mlir:10:16
  assign _GEN_11 = _GEN_12 ? 1'h1 : _GEN_2;	// ./stencil_2d_out/comp/affine.mlir:10:16
  wire [63:0] _GEN_29 = _ForOP_SM0_iv * 64'h1;
  wire [63:0] _GEN_30 = _GEN_29 + _GEN_26 * 64'h3 + 64'h0;
  wire        _GEN_31 = _GEN_24 ? 1'h1 : 1'h0;	// ./stencil_2d_out/comp/affine.mlir:9:9
  reg         _GEN_32;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_32 <= 1'h0;
    else
      _GEN_32 <= _GEN_24;	// ./stencil_2d_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  wire [63:0] _GEN_33 = _GEN_29 + _GEN_27 * 64'h1 + _GEN_26 * 64'h1E + 64'h0;
  reg         _GEN_34;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_34 <= 1'h0;
    else
      _GEN_34 <= _GEN_24;	// ./stencil_2d_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  reg         _GEN_35;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_35 <= 1'h0;
    else
      _GEN_35 <= _GEN_24;	// ./stencil_2d_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  mul_i32 mul_i32_inst0 (	// ./stencil_2d_out/comp/affine.mlir:13:16
    .a   (filter_p0_rd_data),
    .b   (orig_p0_rd_data),
    .t   (_GEN_35),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst0_out)
  );
  add_i32 add_i32_inst1 (	// ./stencil_2d_out/comp/affine.mlir:14:16
    .a   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .b   (_mul_i32_inst0_out),	// ./stencil_2d_out/comp/affine.mlir:13:16
    .t   (_GEN_12),	// ./stencil_2d_out/comp/affine.mlir:10:16
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst1_out)
  );
  assign _GEN_10 = _GEN_12 ? 1'h1 : 1'h0;	// ./stencil_2d_out/comp/affine.mlir:10:16
  assign _GEN_9 = _GEN_12 ? _add_i32_inst1_out : 32'bx;	// ./stencil_2d_out/comp/affine.mlir:10:16, :14:16
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst1 (
    .p0_rd_en   (_GEN_10),
    .p0_rd_data (_reg_1x64_r0_w1_inst1_p0_rd_data),
    .p1_wr_en   (_GEN_31),
    .p1_wr_data (_GEN_8),
    .t          (_GEN_24),	// ./stencil_2d_out/comp/affine.mlir:9:9
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_8 = _GEN_24 ? _GEN_26 : 64'bx;	// ./stencil_2d_out/comp/affine.mlir:9:9
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst2 (
    .p0_rd_en   (_GEN_10),
    .p0_rd_data (_reg_1x64_r0_w1_inst2_p0_rd_data),
    .p1_wr_en   (_GEN_31),
    .p1_wr_data (_GEN_7),
    .t          (_GEN_24),	// ./stencil_2d_out/comp/affine.mlir:9:9
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_7 = _GEN_24 ? _GEN_27 : 64'bx;	// ./stencil_2d_out/comp/affine.mlir:9:9
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst3 (
    .p0_rd_en   (_GEN_4),
    .p0_rd_data (_reg_1x64_r0_w1_inst3_p0_rd_data),
    .p1_wr_en   (_GEN_6),
    .p1_wr_data (_GEN_5),
    .t          (_GEN_20),	// ./stencil_2d_out/comp/affine.mlir:8:7
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_6 = _GEN_20 ? 1'h1 : 1'h0;	// ./stencil_2d_out/comp/affine.mlir:8:7
  assign _GEN_5 = _GEN_20 ? _GEN_22 : 64'bx;	// ./stencil_2d_out/comp/affine.mlir:8:7
  reg  [5:0]  _GEN_36;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_36 <= {6{1'h0}};
    else
      _GEN_36 <= {_GEN_36[3'h0 +: 5], {1{_GEN_20}}};	// ./stencil_2d_out/comp/affine.mlir:8:7
  end // always_ff @(posedge)
  assign _GEN_4 = _GEN_36[3'h5] ? 1'h1 : 1'h0;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_3 <= 1'h0;
    else
      _GEN_3 <= _GEN_21 | _GEN_13 & _ForOP_SM1_done;	// ./stencil_2d_out/comp/affine.mlir:8:7, :9:9
  end // always_ff @(posedge)
  assign _GEN_2 = _GEN_3 ? 1'h1 : 1'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst4 (
    .p0_rd_en   (_GEN),
    .p0_rd_data (_reg_1x64_r0_w1_inst4_p0_rd_data),
    .p1_wr_en   (_GEN_1),
    .p1_wr_data (_GEN_0),
    .t          (_GEN_16),	// ./stencil_2d_out/comp/affine.mlir:6:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_1 = _GEN_16 ? 1'h1 : 1'h0;	// ./stencil_2d_out/comp/affine.mlir:6:5
  assign _GEN_0 = _GEN_16 ? _ForOP_SM2_iv : 64'bx;	// ./stencil_2d_out/comp/affine.mlir:6:5
  reg  [18:0] _GEN_37;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_37 <= {19{1'h0}};
    else
      _GEN_37 <= {_GEN_37[5'h0 +: 18], {1{_GEN_16}}};	// ./stencil_2d_out/comp/affine.mlir:6:5
  end // always_ff @(posedge)
  assign _GEN = _GEN_37[5'h12] ? 1'h1 : 1'h0;
  wire [63:0] _GEN_38 = _reg_1x64_r0_w1_inst4_p0_rd_data * 64'h1 + 64'h0;
  assign orig_p0_addr_en = _GEN_31;
  assign orig_p0_addr_data = _GEN_24 ? _GEN_33[9:0] : 10'bx;	// ./stencil_2d_out/comp/affine.mlir:9:9
  assign orig_p0_rd_en = _GEN_31;
  assign filter_p0_addr_en = _GEN_31;
  assign filter_p0_addr_data = _GEN_24 ? _GEN_30[3:0] : 4'bx;	// ./stencil_2d_out/comp/affine.mlir:9:9
  assign filter_p0_rd_en = _GEN_31;
  assign sol_p0_addr_en = _GEN_2;
  assign sol_p0_addr_data = _GEN_3 ? _GEN_38[9:0] : 10'bx;
  assign sol_p0_wr_en = _GEN_2;
  assign sol_p0_wr_data = _GEN_3 ? _reg_1x32_r0_w1_inst0_p0_rd_data : 32'bx;
endmodule

