// Generated by CIRCT unknown git version
module fir(	// ./out/comp/affine.mlir:1:3
  output        di_p0_addr_en,
  output [9:0]  di_p0_addr_data,
  output        di_p0_rd_en,
  input  [31:0] di_p0_rd_data,
  output        idx_p0_addr_en,
  output [9:0]  idx_p0_addr_data,
  output        idx_p0_rd_en,
  input  [31:0] idx_p0_rd_data,
  input         t,
                clk,
                rst
);

  wire [31:0] _GEN;
  reg         _GEN_0;
  wire        _GEN_1;
  wire [31:0] _GEN_2;
  wire        _GEN_3;
  wire [31:0] _add_i32_inst1_out;	// ./out/comp/affine.mlir:10:12
  wire [31:0] _mul_i32_inst0_out;	// ./out/comp/affine.mlir:9:12
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_1),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_3),
    .p1_wr_data (_GEN_2),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_3 = t ? 1'h1 : _GEN_1;
  assign _GEN_2 = t ? 32'h0 : _GEN;
  wire        _GEN_4 = t & 1'h1 | _GEN_0 & ~_ForOP_SM0_done;	// ./out/comp/affine.mlir:5:5
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h400),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_4),	// ./out/comp/affine.mlir:5:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  reg  [1:0]  _GEN_5;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_5 <= {2{1'h0}};
    else
      _GEN_5 <= {_GEN_5[1'h0 +: 1], {1{_GEN_4}}};	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  assign _GEN_1 = _GEN_5[1'h1] ? 1'h1 : 1'h0;	// ./out/comp/affine.mlir:6:12
  wire [63:0] _GEN_6 = _ForOP_SM0_iv * 64'h1 + 64'h0;
  wire        _GEN_7 = _GEN_4 ? 1'h1 : 1'h0;	// ./out/comp/affine.mlir:5:5
  reg         _GEN_8;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_8 <= 1'h0;
    else
      _GEN_8 <= _GEN_4;	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  wire [63:0] _GEN_9 = _ForOP_SM0_iv * 64'hFFFFFFFFFFFFFFFF + 64'h3FF;
  reg         _GEN_10;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_10 <= 1'h0;
    else
      _GEN_10 <= _GEN_4;	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_0 <= 1'h0;
    else
      _GEN_0 <= _GEN_4;	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  mul_i32 mul_i32_inst0 (	// ./out/comp/affine.mlir:9:12
    .a   (idx_p0_rd_data),
    .b   (di_p0_rd_data),
    .t   (_GEN_0),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst0_out)
  );
  add_i32 add_i32_inst1 (	// ./out/comp/affine.mlir:10:12
    .a   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .b   (_mul_i32_inst0_out),	// ./out/comp/affine.mlir:9:12
    .t   (_GEN_5[1'h1]),	// ./out/comp/affine.mlir:6:12
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst1_out)
  );
  assign _GEN = _GEN_5[1'h1] ? _add_i32_inst1_out : 32'bx;	// ./out/comp/affine.mlir:6:12, :10:12
  assign di_p0_addr_en = _GEN_7;
  assign di_p0_addr_data = _GEN_4 ? _GEN_9[9:0] : 10'bx;	// ./out/comp/affine.mlir:5:5
  assign di_p0_rd_en = _GEN_7;
  assign idx_p0_addr_en = _GEN_7;
  assign idx_p0_addr_data = _GEN_4 ? _GEN_6[9:0] : 10'bx;	// ./out/comp/affine.mlir:5:5
  assign idx_p0_rd_en = _GEN_7;
endmodule

