// Generated by CIRCT unknown git version
module gesummv(	// ./comp/affine.mlir:1:3
  input  [31:0] alpha,
                beta,
  output        tmp_p0_addr_en,
  output [2:0]  tmp_p0_addr_data,
  output        tmp_p0_wr_en,
  output [31:0] tmp_p0_wr_data,
  output        A_p0_addr_en,
  output [5:0]  A_p0_addr_data,
  output        A_p0_rd_en,
  input  [31:0] A_p0_rd_data,
  output        B_p0_addr_en,
  output [5:0]  B_p0_addr_data,
  output        B_p0_rd_en,
  input  [31:0] B_p0_rd_data,
  output        X_p0_addr_en,
  output [2:0]  X_p0_addr_data,
  output        X_p0_rd_en,
  input  [31:0] X_p0_rd_data,
  output        Y_p0_addr_en,
  output [2:0]  Y_p0_addr_data,
  output        Y_p0_wr_en,
  output [31:0] Y_p0_wr_data,
  input         t,
                clk,
                rst
);

  wire        _GEN;
  wire [31:0] _GEN_0;
  wire        _GEN_1;
  wire [31:0] _GEN_2;
  wire        _GEN_3;
  wire [63:0] _GEN_4;
  wire [31:0] _GEN_5;
  wire [31:0] _GEN_6;
  wire        _GEN_7;
  wire [63:0] _GEN_8;
  wire        _GEN_9;
  wire        _GEN_10;
  wire        _GEN_11;
  wire [63:0] _GEN_12;
  wire [31:0] _GEN_13;
  wire        _GEN_14;
  wire [31:0] _GEN_15;
  wire        _GEN_16;
  wire        _GEN_17;
  reg         _GEN_18;
  wire [31:0] _GEN_19;
  wire        _GEN_20;
  wire [31:0] _GEN_21;
  wire        _GEN_22;
  wire [31:0] _reg_1x32_r0_w1_inst8_p0_rd_data;
  wire [31:0] _reg_1x32_r0_w1_inst7_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst6_p0_rd_data;
  wire [31:0] _add_i32_inst6_out;	// ./comp/affine.mlir:29:12
  wire [31:0] _mul_i32_inst5_out;	// ./comp/affine.mlir:28:12
  wire [31:0] _reg_1x32_r0_w1_inst5_p0_rd_data;
  wire [31:0] _mul_i32_inst4_out;	// ./comp/affine.mlir:27:12
  wire [31:0] _reg_1x32_r0_w1_inst4_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst3_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst2_p0_rd_data;
  wire [31:0] _add_i32_inst3_out;	// ./comp/affine.mlir:21:15
  wire [31:0] _add_i32_inst2_out;	// ./comp/affine.mlir:18:15
  wire [31:0] _mul_i32_inst1_out;	// ./comp/affine.mlir:16:15
  wire [31:0] _mul_i32_inst0_out;	// ./comp/affine.mlir:14:14
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire [63:0] _ForOP_SM1_iv;
  wire        _ForOP_SM1_done;
  wire [31:0] _reg_1x32_r0_w1_inst1_p0_rd_data;
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_14),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_20),
    .p1_wr_data (_GEN_19),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst1 (
    .p0_rd_en   (_GEN_17),
    .p0_rd_data (_reg_1x32_r0_w1_inst1_p0_rd_data),
    .p1_wr_en   (_GEN_22),
    .p1_wr_data (_GEN_21),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  wire        _GEN_23 = t & 1'h1;
  wire        _GEN_24 = _GEN_23 | _GEN & ~_ForOP_SM1_done;	// ./comp/affine.mlir:8:5
  wire        _GEN_25 = t & ~(1'h1);
  wire [31:0] _GEN_26 = _GEN_23 ? alpha : _reg_1x32_r0_w1_inst7_p0_rd_data;
  wire [31:0] _GEN_27 = _GEN_23 ? beta : _reg_1x32_r0_w1_inst8_p0_rd_data;
  ForOp_state_machine1 ForOP_SM1 (
    .lb    (64'h0),
    .ub    (64'h8),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_24),	// ./comp/affine.mlir:8:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM1_iv),
    .done  (_ForOP_SM1_done)
  );
  reg         _GEN_28;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_28 <= 1'h0;
    else
      _GEN_28 <= _GEN_24;	// ./comp/affine.mlir:8:5
  end // always_ff @(posedge)
  assign _GEN_22 = _GEN_28 ? 1'h1 : _GEN_16;
  assign _GEN_21 = _GEN_28 ? 32'h0 : _GEN_15;
  assign _GEN_20 = _GEN_28 ? 1'h1 : _GEN_16;
  assign _GEN_19 = _GEN_28 ? 32'h0 : _GEN_13;
  wire        _GEN_29 = 64'h0 < 64'h8;
  wire        _GEN_30 = _GEN_24 & _GEN_29;	// ./comp/affine.mlir:8:5
  wire        _GEN_31 = _GEN_30 | _GEN_18 & ~_ForOP_SM0_done;	// ./comp/affine.mlir:11:7
  wire        _GEN_32 = _GEN_24 & ~_GEN_29;	// ./comp/affine.mlir:8:5
  wire        _GEN_33 = _GEN_32 | _GEN_18 & _ForOP_SM0_done;	// ./comp/affine.mlir:11:7
  wire [63:0] _GEN_34 = _GEN_30 ? _ForOP_SM1_iv : _reg_1x64_r0_w1_inst2_p0_rd_data;
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h8),
    .step  (64'h1),
    .start (_GEN_24),	// ./comp/affine.mlir:8:5
    .next  (_GEN_31),	// ./comp/affine.mlir:11:7
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  wire [63:0] _GEN_35 = _ForOP_SM0_iv * 64'h1;
  wire [63:0] _GEN_36 = _GEN_35 + 64'h0;
  wire        _GEN_37 = _GEN_31 ? 1'h1 : 1'h0;	// ./comp/affine.mlir:11:7
  reg         _GEN_38;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_38 <= 1'h0;
    else
      _GEN_38 <= _GEN_31;	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  wire [63:0] _GEN_39 = _GEN_34 * 64'h1 + _ForOP_SM0_iv * 64'h0 + 64'h0;
  wire [63:0] _GEN_40 = _GEN_34 * 64'h0 + _GEN_35 + 64'h0;
  wire [5:0]  _GEN_41 = {_GEN_39[2:0], _GEN_40[2:0]};	// ./comp/affine.mlir:13:14
  reg         _GEN_42;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_42 <= 1'h0;
    else
      _GEN_42 <= _GEN_31;	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_18 <= 1'h0;
    else
      _GEN_18 <= _GEN_31;	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  mul_i32 mul_i32_inst0 (	// ./comp/affine.mlir:14:14
    .a   (A_p0_rd_data),
    .b   (X_p0_rd_data),
    .t   (_GEN_18),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst0_out)
  );
  reg         _GEN_43;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_43 <= 1'h0;
    else
      _GEN_43 <= _GEN_31;	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  mul_i32 mul_i32_inst1 (	// ./comp/affine.mlir:16:15
    .a   (B_p0_rd_data),
    .b   (X_p0_rd_data),
    .t   (_GEN_18),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst1_out)
  );
  reg  [1:0]  _GEN_44;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_44 <= {2{1'h0}};
    else
      _GEN_44 <= {_GEN_44[1'h0 +: 1], {1{_GEN_31}}};	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  assign _GEN_17 = _GEN_44[1'h1] ? 1'h1 : _GEN_10;	// ./comp/affine.mlir:17:15
  add_i32 add_i32_inst2 (	// ./comp/affine.mlir:18:15
    .a   (_reg_1x32_r0_w1_inst1_p0_rd_data),
    .b   (_mul_i32_inst0_out),	// ./comp/affine.mlir:14:14
    .t   (_GEN_44[1'h1]),	// ./comp/affine.mlir:17:15
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst2_out)
  );
  assign _GEN_16 = _GEN_44[1'h1] ? 1'h1 : 1'h0;	// ./comp/affine.mlir:17:15
  assign _GEN_15 = _GEN_44[1'h1] ? _add_i32_inst2_out : 32'bx;	// ./comp/affine.mlir:17:15, :18:15
  assign _GEN_14 = _GEN_44[1'h1] ? 1'h1 : _GEN_10;	// ./comp/affine.mlir:17:15
  add_i32 add_i32_inst3 (	// ./comp/affine.mlir:21:15
    .a   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .b   (_mul_i32_inst1_out),	// ./comp/affine.mlir:16:15
    .t   (_GEN_44[1'h1]),	// ./comp/affine.mlir:17:15
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst3_out)
  );
  assign _GEN_13 = _GEN_44[1'h1] ? _add_i32_inst3_out : 32'bx;	// ./comp/affine.mlir:17:15, :21:15
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst2 (
    .p0_rd_en   (_GEN_11),
    .p0_rd_data (_reg_1x64_r0_w1_inst2_p0_rd_data),
    .p1_wr_en   (_GEN_37),
    .p1_wr_data (_GEN_12),
    .t          (_GEN_31),	// ./comp/affine.mlir:11:7
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_12 = _GEN_31 ? _GEN_34 : 64'bx;	// ./comp/affine.mlir:11:7
  assign _GEN_11 = _GEN_18 ? 1'h1 : 1'h0;
  reg  [1:0]  _GEN_45;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_45 <= {2{1'h0}};
    else
      _GEN_45 <= {_GEN_45[1'h0 +: 1], {1{_GEN_33}}};	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  assign _GEN_10 = _GEN_45[1'h1] ? 1'h1 : 1'h0;	// ./comp/affine.mlir:24:12
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst3 (
    .p0_rd_en   (_GEN_7),
    .p0_rd_data (_reg_1x64_r0_w1_inst3_p0_rd_data),
    .p1_wr_en   (_GEN_9),
    .p1_wr_data (_GEN_8),
    .t          (_GEN_24),	// ./comp/affine.mlir:8:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_9 = _GEN_24 ? 1'h1 : 1'h0;	// ./comp/affine.mlir:8:5
  assign _GEN_8 = _GEN_24 ? _ForOP_SM1_iv : 64'bx;	// ./comp/affine.mlir:8:5
  reg  [9:0]  _GEN_46;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_46 <= {10{1'h0}};
    else
      _GEN_46 <= {_GEN_46[4'h0 +: 9], {1{_GEN_24}}};	// ./comp/affine.mlir:8:5
  end // always_ff @(posedge)
  assign _GEN_7 = _GEN_46[4'h9] ? 1'h1 : 1'h0;
  wire [63:0] _GEN_47 = _reg_1x64_r0_w1_inst3_p0_rd_data * 64'h1 + 64'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst4 (
    .p0_rd_en   (_GEN_7),
    .p0_rd_data (_reg_1x32_r0_w1_inst4_p0_rd_data),
    .p1_wr_en   (_GEN_9),
    .p1_wr_data (_GEN_6),
    .t          (_GEN_24),	// ./comp/affine.mlir:8:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_6 = _GEN_24 ? _GEN_26 : 32'bx;	// ./comp/affine.mlir:8:5
  mul_i32 mul_i32_inst4 (	// ./comp/affine.mlir:27:12
    .a   (_reg_1x32_r0_w1_inst4_p0_rd_data),
    .b   (_reg_1x32_r0_w1_inst1_p0_rd_data),
    .t   (_GEN_45[1'h1]),	// ./comp/affine.mlir:24:12
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst4_out)
  );
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst5 (
    .p0_rd_en   (_GEN_7),
    .p0_rd_data (_reg_1x32_r0_w1_inst5_p0_rd_data),
    .p1_wr_en   (_GEN_9),
    .p1_wr_data (_GEN_5),
    .t          (_GEN_24),	// ./comp/affine.mlir:8:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_5 = _GEN_24 ? _GEN_27 : 32'bx;	// ./comp/affine.mlir:8:5
  mul_i32 mul_i32_inst5 (	// ./comp/affine.mlir:28:12
    .a   (_reg_1x32_r0_w1_inst5_p0_rd_data),
    .b   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .t   (_GEN_45[1'h1]),	// ./comp/affine.mlir:24:12
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst5_out)
  );
  reg  [2:0]  _GEN_48;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_48 <= {3{1'h0}};
    else
      _GEN_48 <= {_GEN_48[2'h0 +: 2], {1{_GEN_33}}};	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  add_i32 add_i32_inst6 (	// ./comp/affine.mlir:29:12
    .a   (_mul_i32_inst4_out),	// ./comp/affine.mlir:27:12
    .b   (_mul_i32_inst5_out),	// ./comp/affine.mlir:28:12
    .t   (_GEN_48[2'h2]),	// ./comp/affine.mlir:29:12
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst6_out)
  );
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst6 (
    .p0_rd_en   (_GEN_3),
    .p0_rd_data (_reg_1x64_r0_w1_inst6_p0_rd_data),
    .p1_wr_en   (_GEN_9),
    .p1_wr_data (_GEN_4),
    .t          (_GEN_24),	// ./comp/affine.mlir:8:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_4 = _GEN_24 ? _ForOP_SM1_iv : 64'bx;	// ./comp/affine.mlir:8:5
  reg  [10:0] _GEN_49;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_49 <= {11{1'h0}};
    else
      _GEN_49 <= {_GEN_49[4'h0 +: 10], {1{_GEN_24}}};	// ./comp/affine.mlir:8:5
  end // always_ff @(posedge)
  assign _GEN_3 = _GEN_49[4'hA] ? 1'h1 : 1'h0;
  wire [63:0] _GEN_50 = _reg_1x64_r0_w1_inst6_p0_rd_data * 64'h1 + 64'h0;
  wire        _GEN_51 = _GEN_48[2'h2] ? 1'h1 : 1'h0;	// ./comp/affine.mlir:29:12
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst7 (
    .p0_rd_en   (_GEN_1),
    .p0_rd_data (_reg_1x32_r0_w1_inst7_p0_rd_data),
    .p1_wr_en   (_GEN_9),
    .p1_wr_data (_GEN_2),
    .t          (_GEN_24),	// ./comp/affine.mlir:8:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_2 = _GEN_24 ? _GEN_26 : 32'bx;	// ./comp/affine.mlir:8:5
  reg  [17:0] _GEN_52;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_52 <= {18{1'h0}};
    else
      _GEN_52 <= {_GEN_52[5'h0 +: 17], {1{_GEN_24}}};	// ./comp/affine.mlir:8:5
  end // always_ff @(posedge)
  assign _GEN_1 = _GEN_52[5'h11] ? 1'h1 : 1'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst8 (
    .p0_rd_en   (_GEN_1),
    .p0_rd_data (_reg_1x32_r0_w1_inst8_p0_rd_data),
    .p1_wr_en   (_GEN_9),
    .p1_wr_data (_GEN_0),
    .t          (_GEN_24),	// ./comp/affine.mlir:8:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_0 = _GEN_24 ? _GEN_27 : 32'bx;	// ./comp/affine.mlir:8:5
  reg  [9:0]  _GEN_53;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_53 <= {10{1'h0}};
    else
      _GEN_53 <= {_GEN_53[4'h0 +: 9], {1{_GEN_33}}};	// ./comp/affine.mlir:11:7
  end // always_ff @(posedge)
  assign _GEN = _GEN_53[4'h9];
  assign tmp_p0_addr_en = _GEN_10;
  assign tmp_p0_addr_data = _GEN_45[1'h1] ? _GEN_47[2:0] : 3'bx;	// ./comp/affine.mlir:24:12
  assign tmp_p0_wr_en = _GEN_10;
  assign tmp_p0_wr_data = _GEN_45[1'h1] ? _reg_1x32_r0_w1_inst1_p0_rd_data : 32'bx;	// ./comp/affine.mlir:24:12
  assign A_p0_addr_en = _GEN_37;
  assign A_p0_addr_data = _GEN_31 ? _GEN_41 : 6'bx;	// ./comp/affine.mlir:11:7, :13:14
  assign A_p0_rd_en = _GEN_37;
  assign B_p0_addr_en = _GEN_37;
  assign B_p0_addr_data = _GEN_31 ? _GEN_41 : 6'bx;	// ./comp/affine.mlir:11:7, :13:14
  assign B_p0_rd_en = _GEN_37;
  assign X_p0_addr_en = _GEN_37;
  assign X_p0_addr_data = _GEN_31 ? _GEN_36[2:0] : 3'bx;	// ./comp/affine.mlir:11:7
  assign X_p0_rd_en = _GEN_37;
  assign Y_p0_addr_en = _GEN_51;
  assign Y_p0_addr_data = _GEN_48[2'h2] ? _GEN_50[2:0] : 3'bx;	// ./comp/affine.mlir:29:12
  assign Y_p0_wr_en = _GEN_51;
  assign Y_p0_wr_data = _GEN_48[2'h2] ? _add_i32_inst6_out : 32'bx;	// ./comp/affine.mlir:29:12
endmodule

