// Generated by CIRCT unknown git version
module matrix(	// ./matrix_out/comp/affine.mlir:1:3
  output        inA_p0_addr_en,
  output [9:0]  inA_p0_addr_data,
  output        inA_p0_rd_en,
  input  [31:0] inA_p0_rd_data,
  output        inB_p0_addr_en,
  output [9:0]  inB_p0_addr_data,
  output        inB_p0_rd_en,
  input  [31:0] inB_p0_rd_data,
  output        outC_p0_addr_en,
  output [9:0]  outC_p0_addr_data,
  output        outC_p0_wr_en,
  output [31:0] outC_p0_wr_data,
  input         t,
                clk,
                rst
);

  wire [63:0] _GEN;
  wire [63:0] _GEN_0;
  wire        _GEN_1;
  wire [63:0] _GEN_2;
  wire        _GEN_3;
  wire        _GEN_4;
  reg         _GEN_5;
  wire [63:0] _GEN_6;
  wire [63:0] _GEN_7;
  wire [31:0] _GEN_8;
  wire        _GEN_9;
  wire        _GEN_10;
  wire        _GEN_11;	// ./matrix_out/comp/affine.mlir:10:16
  wire [31:0] _GEN_12;
  wire        _GEN_13;
  wire        _GEN_14;	// ./matrix_out/comp/affine.mlir:7:7
  wire [63:0] _reg_1x64_r0_w1_inst5_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst4_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst3_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst2_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst1_p0_rd_data;
  wire [31:0] _add_i32_inst1_out;	// ./matrix_out/comp/affine.mlir:14:16
  wire [31:0] _mul_i32_inst0_out;	// ./matrix_out/comp/affine.mlir:13:16
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire [63:0] _ForOP_SM1_iv;
  wire        _ForOP_SM1_done;
  wire [63:0] _ForOP_SM2_iv;
  wire        _ForOP_SM2_done;
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_10),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_13),
    .p1_wr_data (_GEN_12),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  wire        _GEN_15 = t & 1'h1 | _GEN_14 & ~_ForOP_SM2_done;	// ./matrix_out/comp/affine.mlir:6:5, :7:7
  ForOp_state_machine2 ForOP_SM2 (
    .lb    (64'h0),
    .ub    (64'h20),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_15),	// ./matrix_out/comp/affine.mlir:6:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM2_iv),
    .done  (_ForOP_SM2_done)
  );
  wire        _GEN_16 = 64'h0 < 64'h20;
  wire        _GEN_17 = _GEN_15 & _GEN_16;	// ./matrix_out/comp/affine.mlir:6:5
  wire        _GEN_18 = _GEN_17 | _GEN_5 & ~_ForOP_SM1_done;	// ./matrix_out/comp/affine.mlir:7:7
  wire        _GEN_19 = _GEN_15 & ~_GEN_16;	// ./matrix_out/comp/affine.mlir:6:5
  assign _GEN_14 = _GEN_19 | _GEN_5 & _ForOP_SM1_done;	// ./matrix_out/comp/affine.mlir:7:7
  wire [63:0] _GEN_20 = _GEN_17 ? _ForOP_SM2_iv : _reg_1x64_r0_w1_inst5_p0_rd_data;
  ForOp_state_machine1 ForOP_SM1 (
    .lb    (64'h0),
    .ub    (64'h20),
    .step  (64'h1),
    .start (_GEN_15),	// ./matrix_out/comp/affine.mlir:6:5
    .next  (_GEN_18),	// ./matrix_out/comp/affine.mlir:7:7
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM1_iv),
    .done  (_ForOP_SM1_done)
  );
  reg         _GEN_21;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_21 <= 1'h0;
    else
      _GEN_21 <= _GEN_18;	// ./matrix_out/comp/affine.mlir:7:7
  end // always_ff @(posedge)
  assign _GEN_13 = _GEN_21 ? 1'h1 : _GEN_9;
  assign _GEN_12 = _GEN_21 ? 32'h0 : _GEN_8;
  wire        _GEN_22 = _GEN_18 & _GEN_16;	// ./matrix_out/comp/affine.mlir:7:7
  wire        _GEN_23 = _GEN_22 | _GEN_11 & ~_ForOP_SM0_done;	// ./matrix_out/comp/affine.mlir:9:9, :10:16
  wire        _GEN_24 = _GEN_18 & ~_GEN_16;	// ./matrix_out/comp/affine.mlir:7:7
  wire [63:0] _GEN_25 = _GEN_22 ? _GEN_20 : _reg_1x64_r0_w1_inst1_p0_rd_data;
  wire [63:0] _GEN_26 = _GEN_22 ? _ForOP_SM1_iv : _reg_1x64_r0_w1_inst2_p0_rd_data;
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h20),
    .step  (64'h1),
    .start (_GEN_18),	// ./matrix_out/comp/affine.mlir:7:7
    .next  (_GEN_23),	// ./matrix_out/comp/affine.mlir:9:9
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  reg  [1:0]  _GEN_27;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_27 <= {2{1'h0}};
    else
      _GEN_27 <= {_GEN_27[1'h0 +: 1], {1{_GEN_23}}};	// ./matrix_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  assign _GEN_11 = _GEN_27[1'h1];	// ./matrix_out/comp/affine.mlir:10:16
  assign _GEN_10 = _GEN_11 ? 1'h1 : _GEN_4;	// ./matrix_out/comp/affine.mlir:10:16
  wire [63:0] _GEN_28 = _ForOP_SM0_iv * 64'h0;
  wire [63:0] _GEN_29 = _GEN_25 * 64'h1 + _GEN_28 + 64'h0;
  wire [63:0] _GEN_30 = _ForOP_SM0_iv * 64'h1;
  wire [63:0] _GEN_31 = _GEN_25 * 64'h0 + _GEN_30 + 64'h0;
  wire        _GEN_32 = _GEN_23 ? 1'h1 : 1'h0;	// ./matrix_out/comp/affine.mlir:9:9
  reg         _GEN_33;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_33 <= 1'h0;
    else
      _GEN_33 <= _GEN_23;	// ./matrix_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  wire [63:0] _GEN_34 = _GEN_30 + _GEN_26 * 64'h0 + 64'h0;
  wire [63:0] _GEN_35 = _GEN_28 + _GEN_26 * 64'h1 + 64'h0;
  reg         _GEN_36;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_36 <= 1'h0;
    else
      _GEN_36 <= _GEN_23;	// ./matrix_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  reg         _GEN_37;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_37 <= 1'h0;
    else
      _GEN_37 <= _GEN_23;	// ./matrix_out/comp/affine.mlir:9:9
  end // always_ff @(posedge)
  mul_i32 mul_i32_inst0 (	// ./matrix_out/comp/affine.mlir:13:16
    .a   (inA_p0_rd_data),
    .b   (inB_p0_rd_data),
    .t   (_GEN_37),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst0_out)
  );
  add_i32 add_i32_inst1 (	// ./matrix_out/comp/affine.mlir:14:16
    .a   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .b   (_mul_i32_inst0_out),	// ./matrix_out/comp/affine.mlir:13:16
    .t   (_GEN_11),	// ./matrix_out/comp/affine.mlir:10:16
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst1_out)
  );
  assign _GEN_9 = _GEN_11 ? 1'h1 : 1'h0;	// ./matrix_out/comp/affine.mlir:10:16
  assign _GEN_8 = _GEN_11 ? _add_i32_inst1_out : 32'bx;	// ./matrix_out/comp/affine.mlir:10:16, :14:16
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst1 (
    .p0_rd_en   (_GEN_9),
    .p0_rd_data (_reg_1x64_r0_w1_inst1_p0_rd_data),
    .p1_wr_en   (_GEN_32),
    .p1_wr_data (_GEN_7),
    .t          (_GEN_23),	// ./matrix_out/comp/affine.mlir:9:9
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_7 = _GEN_23 ? _GEN_25 : 64'bx;	// ./matrix_out/comp/affine.mlir:9:9
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst2 (
    .p0_rd_en   (_GEN_9),
    .p0_rd_data (_reg_1x64_r0_w1_inst2_p0_rd_data),
    .p1_wr_en   (_GEN_32),
    .p1_wr_data (_GEN_6),
    .t          (_GEN_23),	// ./matrix_out/comp/affine.mlir:9:9
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_6 = _GEN_23 ? _GEN_26 : 64'bx;	// ./matrix_out/comp/affine.mlir:9:9
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_5 <= 1'h0;
    else
      _GEN_5 <= _GEN_24 | _GEN_11 & _ForOP_SM0_done;	// ./matrix_out/comp/affine.mlir:9:9, :10:16
  end // always_ff @(posedge)
  assign _GEN_4 = _GEN_5 ? 1'h1 : 1'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst3 (
    .p0_rd_en   (_GEN_1),
    .p0_rd_data (_reg_1x64_r0_w1_inst3_p0_rd_data),
    .p1_wr_en   (_GEN_3),
    .p1_wr_data (_GEN_2),
    .t          (_GEN_18),	// ./matrix_out/comp/affine.mlir:7:7
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_3 = _GEN_18 ? 1'h1 : 1'h0;	// ./matrix_out/comp/affine.mlir:7:7
  assign _GEN_2 = _GEN_18 ? _GEN_20 : 64'bx;	// ./matrix_out/comp/affine.mlir:7:7
  reg  [64:0] _GEN_38;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_38 <= {65{1'h0}};
    else
      _GEN_38 <= {_GEN_38[7'h0 +: 64], {1{_GEN_18}}};	// ./matrix_out/comp/affine.mlir:7:7
  end // always_ff @(posedge)
  assign _GEN_1 = _GEN_38[7'h40] ? 1'h1 : 1'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst4 (
    .p0_rd_en   (_GEN_1),
    .p0_rd_data (_reg_1x64_r0_w1_inst4_p0_rd_data),
    .p1_wr_en   (_GEN_3),
    .p1_wr_data (_GEN_0),
    .t          (_GEN_18),	// ./matrix_out/comp/affine.mlir:7:7
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_0 = _GEN_18 ? _ForOP_SM1_iv : 64'bx;	// ./matrix_out/comp/affine.mlir:7:7
  wire [63:0] _GEN_39 =
    _reg_1x64_r0_w1_inst3_p0_rd_data * 64'h1 + _reg_1x64_r0_w1_inst4_p0_rd_data * 64'h0
    + 64'h0;
  wire [63:0] _GEN_40 =
    _reg_1x64_r0_w1_inst3_p0_rd_data * 64'h0 + _reg_1x64_r0_w1_inst4_p0_rd_data * 64'h1
    + 64'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst5 (
    .p0_rd_en   (_GEN_1),
    .p0_rd_data (_reg_1x64_r0_w1_inst5_p0_rd_data),
    .p1_wr_en   (_GEN_3),
    .p1_wr_data (_GEN),
    .t          (_GEN_18),	// ./matrix_out/comp/affine.mlir:7:7
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN = _GEN_18 ? _GEN_20 : 64'bx;	// ./matrix_out/comp/affine.mlir:7:7
  assign inA_p0_addr_en = _GEN_32;
  assign inA_p0_addr_data = _GEN_23 ? {_GEN_29[4:0], _GEN_31[4:0]} : 10'bx;	// ./matrix_out/comp/affine.mlir:9:9, :11:16
  assign inA_p0_rd_en = _GEN_32;
  assign inB_p0_addr_en = _GEN_32;
  assign inB_p0_addr_data = _GEN_23 ? {_GEN_34[4:0], _GEN_35[4:0]} : 10'bx;	// ./matrix_out/comp/affine.mlir:9:9, :12:16
  assign inB_p0_rd_en = _GEN_32;
  assign outC_p0_addr_en = _GEN_4;
  assign outC_p0_addr_data = _GEN_5 ? {_GEN_39[4:0], _GEN_40[4:0]} : 10'bx;	// ./matrix_out/comp/affine.mlir:18:9
  assign outC_p0_wr_en = _GEN_4;
  assign outC_p0_wr_data = _GEN_5 ? _reg_1x32_r0_w1_inst0_p0_rd_data : 32'bx;
endmodule

