// Generated by CIRCT unknown git version
module sumi3_mem(	// ./out/comp/affine.mlir:1:3
  output        a_p0_addr_en,
  output [9:0]  a_p0_addr_data,
  output        a_p0_rd_en,
  input  [31:0] a_p0_rd_data,
  input         t,
                clk,
                rst
);

  wire [31:0] _GEN;
  wire        _GEN_0;
  wire [31:0] _GEN_1;
  wire        _GEN_2;
  reg         _GEN_3;
  wire        _GEN_4;
  wire [31:0] _GEN_5;
  wire        _GEN_6;
  wire [31:0] _add_i32_inst2_out;	// ./out/comp/affine.mlir:10:12
  wire [31:0] _mul_i32_inst1_out;	// ./out/comp/affine.mlir:9:12
  wire [31:0] _reg_1x32_r0_w1_inst1_p0_rd_data;
  wire [31:0] _mul_i32_inst0_out;	// ./out/comp/affine.mlir:8:12
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_4),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_6),
    .p1_wr_data (_GEN_5),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_6 = t ? 1'h1 : _GEN_4;
  assign _GEN_5 = t ? 32'h0 : _GEN;
  wire        _GEN_7 = t & 1'h1 | _GEN_3 & ~_ForOP_SM0_done;	// ./out/comp/affine.mlir:5:5
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h400),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_7),	// ./out/comp/affine.mlir:5:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  wire [63:0] _GEN_8 = _ForOP_SM0_iv * 64'h1 + 64'h0;
  wire        _GEN_9 = _GEN_7 ? 1'h1 : 1'h0;	// ./out/comp/affine.mlir:5:5
  reg         _GEN_10;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_10 <= 1'h0;
    else
      _GEN_10 <= _GEN_7;	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  reg  [2:0]  _GEN_11;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_11 <= {3{1'h0}};
    else
      _GEN_11 <= {_GEN_11[2'h0 +: 2], {1{_GEN_7}}};	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  assign _GEN_4 = _GEN_11[2'h2] ? 1'h1 : 1'h0;	// ./out/comp/affine.mlir:7:12
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_3 <= 1'h0;
    else
      _GEN_3 <= _GEN_7;	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  mul_i32 mul_i32_inst0 (	// ./out/comp/affine.mlir:8:12
    .a   (a_p0_rd_data),
    .b   (a_p0_rd_data),
    .t   (_GEN_3),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst0_out)
  );
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst1 (
    .p0_rd_en   (_GEN_0),
    .p0_rd_data (_reg_1x32_r0_w1_inst1_p0_rd_data),
    .p1_wr_en   (_GEN_2),
    .p1_wr_data (_GEN_1),
    .t          (_GEN_7),	// ./out/comp/affine.mlir:5:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_2 = _GEN_3 ? 1'h1 : 1'h0;
  assign _GEN_1 = _GEN_3 ? a_p0_rd_data : 32'bx;
  reg  [1:0]  _GEN_12;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_12 <= {2{1'h0}};
    else
      _GEN_12 <= {_GEN_12[1'h0 +: 1], {1{_GEN_7}}};	// ./out/comp/affine.mlir:5:5
  end // always_ff @(posedge)
  assign _GEN_0 = _GEN_12[1'h1] ? 1'h1 : 1'h0;	// ./out/comp/affine.mlir:9:12
  mul_i32 mul_i32_inst1 (	// ./out/comp/affine.mlir:9:12
    .a   (_mul_i32_inst0_out),	// ./out/comp/affine.mlir:8:12
    .b   (_reg_1x32_r0_w1_inst1_p0_rd_data),
    .t   (_GEN_12[1'h1]),	// ./out/comp/affine.mlir:9:12
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst1_out)
  );
  add_i32 add_i32_inst2 (	// ./out/comp/affine.mlir:10:12
    .a   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .b   (_mul_i32_inst1_out),	// ./out/comp/affine.mlir:9:12
    .t   (_GEN_11[2'h2]),	// ./out/comp/affine.mlir:7:12
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst2_out)
  );
  assign _GEN = _GEN_11[2'h2] ? _add_i32_inst2_out : 32'bx;	// ./out/comp/affine.mlir:7:12, :10:12
  assign a_p0_addr_en = _GEN_9;
  assign a_p0_addr_data = _GEN_7 ? _GEN_8[9:0] : 10'bx;	// ./out/comp/affine.mlir:5:5
  assign a_p0_rd_en = _GEN_9;
endmodule

