// Generated by CIRCT unknown git version
module vector_rescale(	// ./vector_rescale_out/comp/affine.mlir:1:1
  output        a_p0_addr_en,
  output [9:0]  a_p0_addr_data,
  output        a_p0_rd_en,
  input  [31:0] a_p0_rd_data,
                c,
  output        b_p0_addr_en,
  output [9:0]  b_p0_addr_data,
  output        b_p0_wr_en,
  output [31:0] b_p0_wr_data,
  input         t,
                clk,
                rst
);

  wire        _GEN;
  wire        _GEN_0;
  wire [31:0] _GEN_1;
  wire        _GEN_2;
  wire [63:0] _GEN_3;
  wire        _GEN_4;
  wire [31:0] _GEN_5;
  wire [31:0] _reg_1x32_r0_w1_inst2_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst1_p0_rd_data;
  wire [31:0] _mul_i32_inst0_out;	// ./vector_rescale_out/comp/affine.mlir:4:12
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire        _GEN_6 = t & 1'h1;
  wire        _GEN_7 = _GEN_6 | _GEN_0 & ~_ForOP_SM0_done;	// ./vector_rescale_out/comp/affine.mlir:2:5
  wire        _GEN_8 = t & ~(1'h1);
  wire [31:0] _GEN_9 = _GEN_6 ? c : _reg_1x32_r0_w1_inst2_p0_rd_data;
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h400),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_7),	// ./vector_rescale_out/comp/affine.mlir:2:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  wire [63:0] _GEN_10 = _ForOP_SM0_iv * 64'h1 + 64'h0;
  wire        _GEN_11 = _GEN_7 ? 1'h1 : 1'h0;	// ./vector_rescale_out/comp/affine.mlir:2:5
  reg         _GEN_12;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_12 <= 1'h0;
    else
      _GEN_12 <= _GEN_7;	// ./vector_rescale_out/comp/affine.mlir:2:5
  end // always_ff @(posedge)
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_4),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_11),
    .p1_wr_data (_GEN_5),
    .t          (_GEN_7),	// ./vector_rescale_out/comp/affine.mlir:2:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_5 = _GEN_7 ? _GEN_9 : 32'bx;	// ./vector_rescale_out/comp/affine.mlir:2:5
  reg         _GEN_13;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_13 <= 1'h0;
    else
      _GEN_13 <= _GEN_7;	// ./vector_rescale_out/comp/affine.mlir:2:5
  end // always_ff @(posedge)
  assign _GEN_4 = _GEN_13 ? 1'h1 : 1'h0;
  mul_i32 mul_i32_inst0 (	// ./vector_rescale_out/comp/affine.mlir:4:12
    .a   (a_p0_rd_data),
    .b   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .t   (_GEN_13),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst0_out)
  );
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst1 (
    .p0_rd_en   (_GEN_2),
    .p0_rd_data (_reg_1x64_r0_w1_inst1_p0_rd_data),
    .p1_wr_en   (_GEN_11),
    .p1_wr_data (_GEN_3),
    .t          (_GEN_7),	// ./vector_rescale_out/comp/affine.mlir:2:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_3 = _GEN_7 ? _ForOP_SM0_iv : 64'bx;	// ./vector_rescale_out/comp/affine.mlir:2:5
  reg  [1:0]  _GEN_14;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_14 <= {2{1'h0}};
    else
      _GEN_14 <= {_GEN_14[1'h0 +: 1], {1{_GEN_7}}};	// ./vector_rescale_out/comp/affine.mlir:2:5
  end // always_ff @(posedge)
  assign _GEN_2 = _GEN_14[1'h1] ? 1'h1 : 1'h0;	// ./vector_rescale_out/comp/affine.mlir:5:7
  wire [63:0] _GEN_15 = _reg_1x64_r0_w1_inst1_p0_rd_data * 64'h1 + 64'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst2 (
    .p0_rd_en   (_GEN),
    .p0_rd_data (_reg_1x32_r0_w1_inst2_p0_rd_data),
    .p1_wr_en   (_GEN_11),
    .p1_wr_data (_GEN_1),
    .t          (_GEN_7),	// ./vector_rescale_out/comp/affine.mlir:2:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_1 = _GEN_7 ? _GEN_9 : 32'bx;	// ./vector_rescale_out/comp/affine.mlir:2:5
  reg  [2:0]  _GEN_16;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_16 <= {3{1'h0}};
    else
      _GEN_16 <= {_GEN_16[2'h0 +: 2], {1{_GEN_7}}};	// ./vector_rescale_out/comp/affine.mlir:2:5
  end // always_ff @(posedge)
  assign _GEN_0 = _GEN_16[2'h2];
  assign _GEN = _GEN_0 ? 1'h1 : 1'h0;
  assign a_p0_addr_en = _GEN_11;
  assign a_p0_addr_data = _GEN_7 ? _GEN_10[9:0] : 10'bx;	// ./vector_rescale_out/comp/affine.mlir:2:5
  assign a_p0_rd_en = _GEN_11;
  assign b_p0_addr_en = _GEN_2;
  assign b_p0_addr_data = _GEN_14[1'h1] ? _GEN_15[9:0] : 10'bx;	// ./vector_rescale_out/comp/affine.mlir:5:7
  assign b_p0_wr_en = _GEN_2;
  assign b_p0_wr_data = _GEN_14[1'h1] ? _mul_i32_inst0_out : 32'bx;	// ./vector_rescale_out/comp/affine.mlir:4:12, :5:7
endmodule

