// Generated by CIRCT unknown git version
module matvec(	// ./matvec_out/comp/affine.mlir:1:1
  output        m_p0_addr_en,
  output [5:0]  m_p0_addr_data,
  output        m_p0_rd_en,
  input  [31:0] m_p0_rd_data,
  output        v_p0_addr_en,
  output [2:0]  v_p0_addr_data,
  output        v_p0_rd_en,
  input  [31:0] v_p0_rd_data,
  output        out_p0_addr_en,
  output [2:0]  out_p0_addr_data,
  output        out_p0_wr_en,
  output [31:0] out_p0_wr_data,
  input         t,
                clk,
                rst
);

  wire        _GEN;
  wire [63:0] _GEN_0;
  wire        _GEN_1;
  wire        _GEN_2;
  reg         _GEN_3;
  wire [63:0] _GEN_4;
  wire [31:0] _GEN_5;
  wire        _GEN_6;
  wire        _GEN_7;
  wire        _GEN_8;	// ./matvec_out/comp/affine.mlir:9:14
  wire [31:0] _GEN_9;
  wire        _GEN_10;
  wire [63:0] _reg_1x64_r0_w1_inst2_p0_rd_data;
  wire [63:0] _reg_1x64_r0_w1_inst1_p0_rd_data;
  wire [31:0] _add_i32_inst1_out;	// ./matvec_out/comp/affine.mlir:13:14
  wire [31:0] _mul_i32_inst0_out;	// ./matvec_out/comp/affine.mlir:12:14
  wire [63:0] _ForOP_SM0_iv;
  wire        _ForOP_SM0_done;
  wire [63:0] _ForOP_SM1_iv;
  wire        _ForOP_SM1_done;
  wire [31:0] _reg_1x32_r0_w1_inst0_p0_rd_data;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd32)
  ) reg_1x32_r0_w1_inst0 (
    .p0_rd_en   (_GEN_7),
    .p0_rd_data (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .p1_wr_en   (_GEN_10),
    .p1_wr_data (_GEN_9),
    .t          (t),
    .clk        (clk),
    .rst        (rst)
  );
  wire        _GEN_11 = t & 1'h1 | _GEN_3 & ~_ForOP_SM1_done;	// ./matvec_out/comp/affine.mlir:6:5
  ForOp_state_machine1 ForOP_SM1 (
    .lb    (64'h0),
    .ub    (64'h8),
    .step  (64'h1),
    .start (t),
    .next  (_GEN_11),	// ./matvec_out/comp/affine.mlir:6:5
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM1_iv),
    .done  (_ForOP_SM1_done)
  );
  reg         _GEN_12;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_12 <= 1'h0;
    else
      _GEN_12 <= _GEN_11;	// ./matvec_out/comp/affine.mlir:6:5
  end // always_ff @(posedge)
  assign _GEN_10 = _GEN_12 ? 1'h1 : _GEN_6;
  assign _GEN_9 = _GEN_12 ? 32'h0 : _GEN_5;
  wire        _GEN_13 = 64'h0 < 64'h8;
  wire        _GEN_14 = _GEN_11 & _GEN_13;	// ./matvec_out/comp/affine.mlir:6:5
  wire        _GEN_15 = _GEN_14 | _GEN_8 & ~_ForOP_SM0_done;	// ./matvec_out/comp/affine.mlir:8:7, :9:14
  wire        _GEN_16 = _GEN_11 & ~_GEN_13;	// ./matvec_out/comp/affine.mlir:6:5
  wire [63:0] _GEN_17 = _GEN_14 ? _ForOP_SM1_iv : _reg_1x64_r0_w1_inst1_p0_rd_data;
  ForOp_state_machine0 ForOP_SM0 (
    .lb    (64'h0),
    .ub    (64'h8),
    .step  (64'h1),
    .start (_GEN_11),	// ./matvec_out/comp/affine.mlir:6:5
    .next  (_GEN_15),	// ./matvec_out/comp/affine.mlir:8:7
    .clk   (clk),
    .rst   (rst),
    .iv    (_ForOP_SM0_iv),
    .done  (_ForOP_SM0_done)
  );
  reg  [1:0]  _GEN_18;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_18 <= {2{1'h0}};
    else
      _GEN_18 <= {_GEN_18[1'h0 +: 1], {1{_GEN_15}}};	// ./matvec_out/comp/affine.mlir:8:7
  end // always_ff @(posedge)
  assign _GEN_8 = _GEN_18[1'h1];	// ./matvec_out/comp/affine.mlir:9:14
  assign _GEN_7 = _GEN_8 ? 1'h1 : _GEN_2;	// ./matvec_out/comp/affine.mlir:9:14
  wire [63:0] _GEN_19 = _ForOP_SM0_iv * 64'h1;
  wire [63:0] _GEN_20 = _GEN_19 + 64'h0;
  wire        _GEN_21 = _GEN_15 ? 1'h1 : 1'h0;	// ./matvec_out/comp/affine.mlir:8:7
  reg         _GEN_22;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_22 <= 1'h0;
    else
      _GEN_22 <= _GEN_15;	// ./matvec_out/comp/affine.mlir:8:7
  end // always_ff @(posedge)
  wire [63:0] _GEN_23 = _GEN_17 * 64'h1 + _ForOP_SM0_iv * 64'h0 + 64'h0;
  wire [63:0] _GEN_24 = _GEN_17 * 64'h0 + _GEN_19 + 64'h0;
  reg         _GEN_25;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_25 <= 1'h0;
    else
      _GEN_25 <= _GEN_15;	// ./matvec_out/comp/affine.mlir:8:7
  end // always_ff @(posedge)
  reg         _GEN_26;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_26 <= 1'h0;
    else
      _GEN_26 <= _GEN_15;	// ./matvec_out/comp/affine.mlir:8:7
  end // always_ff @(posedge)
  mul_i32 mul_i32_inst0 (	// ./matvec_out/comp/affine.mlir:12:14
    .a   (v_p0_rd_data),
    .b   (m_p0_rd_data),
    .t   (_GEN_26),
    .clk (clk),
    .rst (rst),
    .out (_mul_i32_inst0_out)
  );
  add_i32 add_i32_inst1 (	// ./matvec_out/comp/affine.mlir:13:14
    .a   (_reg_1x32_r0_w1_inst0_p0_rd_data),
    .b   (_mul_i32_inst0_out),	// ./matvec_out/comp/affine.mlir:12:14
    .t   (_GEN_8),	// ./matvec_out/comp/affine.mlir:9:14
    .clk (clk),
    .rst (rst),
    .out (_add_i32_inst1_out)
  );
  assign _GEN_6 = _GEN_8 ? 1'h1 : 1'h0;	// ./matvec_out/comp/affine.mlir:9:14
  assign _GEN_5 = _GEN_8 ? _add_i32_inst1_out : 32'bx;	// ./matvec_out/comp/affine.mlir:9:14, :13:14
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst1 (
    .p0_rd_en   (_GEN_6),
    .p0_rd_data (_reg_1x64_r0_w1_inst1_p0_rd_data),
    .p1_wr_en   (_GEN_21),
    .p1_wr_data (_GEN_4),
    .t          (_GEN_15),	// ./matvec_out/comp/affine.mlir:8:7
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_4 = _GEN_15 ? _GEN_17 : 64'bx;	// ./matvec_out/comp/affine.mlir:8:7
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_3 <= 1'h0;
    else
      _GEN_3 <= _GEN_16 | _GEN_8 & _ForOP_SM0_done;	// ./matvec_out/comp/affine.mlir:8:7, :9:14
  end // always_ff @(posedge)
  assign _GEN_2 = _GEN_3 ? 1'h1 : 1'h0;
  reg_r0_w1 #(
    .ELEMENT_WIDTH(64'd64)
  ) reg_1x64_r0_w1_inst2 (
    .p0_rd_en   (_GEN),
    .p0_rd_data (_reg_1x64_r0_w1_inst2_p0_rd_data),
    .p1_wr_en   (_GEN_1),
    .p1_wr_data (_GEN_0),
    .t          (_GEN_11),	// ./matvec_out/comp/affine.mlir:6:5
    .clk        (clk),
    .rst        (rst)
  );
  assign _GEN_1 = _GEN_11 ? 1'h1 : 1'h0;	// ./matvec_out/comp/affine.mlir:6:5
  assign _GEN_0 = _GEN_11 ? _ForOP_SM1_iv : 64'bx;	// ./matvec_out/comp/affine.mlir:6:5
  reg  [16:0] _GEN_27;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_27 <= {17{1'h0}};
    else
      _GEN_27 <= {_GEN_27[5'h0 +: 16], {1{_GEN_11}}};	// ./matvec_out/comp/affine.mlir:6:5
  end // always_ff @(posedge)
  assign _GEN = _GEN_27[5'h10] ? 1'h1 : 1'h0;
  wire [63:0] _GEN_28 = _reg_1x64_r0_w1_inst2_p0_rd_data * 64'h1 + 64'h0;
  assign m_p0_addr_en = _GEN_21;
  assign m_p0_addr_data = _GEN_15 ? {_GEN_23[2:0], _GEN_24[2:0]} : 6'bx;	// ./matvec_out/comp/affine.mlir:8:7, :11:14
  assign m_p0_rd_en = _GEN_21;
  assign v_p0_addr_en = _GEN_21;
  assign v_p0_addr_data = _GEN_15 ? _GEN_20[2:0] : 3'bx;	// ./matvec_out/comp/affine.mlir:8:7
  assign v_p0_rd_en = _GEN_21;
  assign out_p0_addr_en = _GEN_2;
  assign out_p0_addr_data = _GEN_3 ? _GEN_28[2:0] : 3'bx;
  assign out_p0_wr_en = _GEN_2;
  assign out_p0_wr_data = _GEN_3 ? _reg_1x32_r0_w1_inst0_p0_rd_data : 32'bx;
endmodule

